FROM python:3.12

WORKDIR /backend

RUN apt-get update && apt-get install -y libgl1-mesa-glx

COPY . /backend

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
